### ISSUE TITLE
Variable order bug?

### ISSUE THREAD

**Issue by korsbo** [SciML/ModelingToolkit.jl#172]
The order in which you give the variables to `ODEFunction` affects the correctness of the solution. 

```julia
@parameters t
@variables a(t) b(t)
@derivatives D'~t
eqs = [
    D(a) ~ - a
    D(b) ~ - 2b
]
de = ODESystem(eqs)
f = ODEFunction(de, [b, a], []) ## [a, b] would give the correct answer.
u0 = [1., 2]

prob = ODEProblem(f, u0, tspan, p)
sol = solve(prob)
plot(sol)
```
![image](https://user-images.githubusercontent.com/16306680/63940821-2ce01700-ca62-11e9-85eb-14c22a0d6482.png)

It seems that the order must follow that of `de.dvs`.

**Comment by wupeifan** [comment]
(I think) this bug was fixed several weeks ago.

**Comment by FHell** [comment]
This is still present on Master.
```julia
using ModelingToolkit
using OrdinaryDiffEq

@parameters t
@variables x(t) y(t)
@derivatives D'~t

eqs = [ D(y) ~ y,
        D(x) ~ x]

de = ODESystem(eqs, t, [x, y], [])
f = ODEFunction(de, [x, y], [])
x0 = [1., 2.]
dx0 = [0., 0.]
f(dx0, x0, nothing, 0.)
println(dx0) # [2., 1.]
```

We're trying to build on top of ODESystems and this is blocking us.

**Comment by ChrisRackauckas** [comment]
Interesting. I guess it's swapping the left hand side variables but not the right hand side equations.

**Comment by ChrisRackauckas** [comment]
Variable order isn't guaranteed. We now have the Pair system for handling this.
