### ISSUE TITLE
`structural_simplify` removes variable it needs later

### ISSUE THREAD

**Issue by wenflo** [SciML/ModelingToolkit.jl#3159]
**Describe the bug 🐞**

Building an ODEProblem from an ODESystem throws an error indicating missing variables, that were optimized away during `structural_simplify`.
By manually combining two of the equations, I can get it to work it for the MWE below.

**Expected behavior**

Building the ODEProblem should work no matter how the equations are specified.

**Minimal Reproducible Example 👇**

Failing version:
```julia
using ModelingToolkit;
@independent_variables t;
@parameters q_in = 1 S_in = 1;
@variables q(t) S(t);
@variables q_sep_out1(t) q_sep_out2(t);
@variables S_sep_out1(t) S_sep_out2(t);
@named sys = ODESystem(Equation[
    # Inout: Flowrate and concentration
    S ~ q_in,
    q ~ S_in,
    # Splitting ratio
    q_sep_out2 ~ 0.5,
    # Split requirement
    q ~ q_sep_out1 + q_sep_out2, # Flows match
    S_sep_out1 ~ S_sep_out2, # Outflows have same concentrations
    ###### Line to be changed
    q*S ~ (q_sep_out1 + q_sep_out2)*S_sep_out2, # Mass conservation of S
    #####
], t, [
    q, S,
    q_sep_out1, q_sep_out2,
    S_sep_out1, S_sep_out2
], [q_in, S_in]
);
sys_simplified = structural_simplify(sys)
prob = ODEProblem(sys_simplified, [], (0, 1)) # Error indicating `S_sep_out1` is missing (see below)

equations(sys_simplified) # Has the missing variable in it
full_equations(sys_simplified) # Does not depend on the missing variable
```
Working version:
```julia
using ModelingToolkit;
@independent_variables t;
@parameters q_in = 1 S_in = 1;
@variables q(t) S(t);
@variables q_sep_out1(t) q_sep_out2(t);
@variables S_sep_out1(t) S_sep_out2(t);
@named sys = ODESystem(Equation[
    # Input: Flowrate and concentration
    S ~ q_in,
    q ~ S_in,
    # Splitting ratio
    q_sep_out2 ~ 0.5,
    # Split requirement
    q ~ q_sep_out1 + q_sep_out2, # Flows match
    S_sep_out1 ~ S_sep_out2, # Outflows have same concentrations
    ######## Changed line
    # Combining the equation from before with the flows matching condition (2 above)
    S_sep_out1 ~ S
    ######## 
], t, [
    q, S,
    q_sep_out1, q_sep_out2,
    S_sep_out1, S_sep_out2
], [q_in, S_in]
);
sys_simplified = structural_simplify(sys)
prob = ODEProblem(sys_simplified, [], (0, 1))
```

**Error & Stacktrace ⚠️**

```julia
┌ Warning: Did not converge after `maxiters = 0` substitutions. Either there is a cycle in the rules or `maxiters` needs to be higher.
└ @ Symbolics ~/.julia/packages/Symbolics/6CYZh/src/variable.jl:528
┌ Warning: Did not converge after `maxiters = 0` substitutions. Either there is a cycle in the rules or `maxiters` needs to be higher.
└ @ Symbolics ~/.julia/packages/Symbolics/6CYZh/src/variable.jl:528
ERROR: ArgumentError: SymbolicUtils.BasicSymbolic{Real}[S_sep_out1(t)] are either missing from the variable map or missing from the system's unknowns/parameters list.
Stacktrace:
  [1] throw_missingvars_in_sys(vars::Vector{SymbolicUtils.BasicSymbolic{Real}})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/utils.jl:771
  [2] promote_to_concrete(vs::Vector{SymbolicUtils.BasicSymbolic{Real}}; tofloat::Bool, use_union::Bool)
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/utils.jl:790
  [3] better_varmap_to_vars(varmap::Dict{…}, vars::Vector{…}; tofloat::Bool, use_union::Bool, container_type::Type, toterm::Function, promotetoconcrete::Nothing, check::Bool, allow_symbolic::Bool)
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/problem_utils.jl:288
  [4] process_SciMLProblem(constructor::Type, sys::NonlinearSystem, u0map::Dict{…}, pmap::Dict{…}; build_initializeprob::Bool, implicit_dae::Bool, t::Nothing, guesses::Dict{…}, warn_initialize_determined::Bool, initialization_eqs::Vector{…}, eval_expression::Bool, eval_module::Module, fully_determined::Bool, check_units::Bool, tofloat::Bool, use_union::Bool, u0_constructor::typeof(identity), du0map::Nothing, check_length::Bool, symbolic_u0::Bool, kwargs::@Kwargs{})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/problem_utils.jl:504
  [5] process_SciMLProblem
    @ ~/.julia/packages/ModelingToolkit/duznJ/src/systems/problem_utils.jl:410 [inlined]
  [6] (NonlinearProblem{true})(sys::NonlinearSystem, u0map::Dict{Any, Any}, parammap::Dict{SymbolicUtils.BasicSymbolic{Real}, Int64}; check_length::Bool, kwargs::@Kwargs{eval_expression::Bool, eval_module::Module})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/nonlinear/nonlinearsystem.jl:431
  [7] NonlinearProblem(::NonlinearSystem, ::Dict{Any, Any}, ::Vararg{Any}; kwargs::@Kwargs{eval_expression::Bool, eval_module::Module})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/nonlinear/nonlinearsystem.jl:422
  [8] ModelingToolkit.InitializationProblem{…}(sys::ODESystem, t::Int64, u0map::Dict{…}, parammap::Dict{…}; guesses::Dict{…}, check_length::Bool, warn_initialize_determined::Bool, initialization_eqs::Vector{…}, fully_determined::Bool, check_units::Bool, kwargs::@Kwargs{…})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:1330
  [9] (ModelingToolkit.InitializationProblem{…})(::ODESystem, ::Int64, ::Vararg{…}; kwargs::@Kwargs{…})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:1232
 [10] ModelingToolkit.InitializationProblem(::ODESystem, ::Int64, ::Vararg{…}; kwargs::@Kwargs{…})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:1220
 [11] process_SciMLProblem(constructor::Type, sys::ODESystem, u0map::Vector{…}, pmap::SciMLBase.NullParameters; build_initializeprob::Bool, implicit_dae::Bool, t::Int64, guesses::Dict{…}, warn_initialize_determined::Bool, initialization_eqs::Vector{…}, eval_expression::Bool, eval_module::Module, fully_determined::Bool, check_units::Bool, tofloat::Bool, use_union::Bool, u0_constructor::typeof(identity), du0map::Nothing, check_length::Bool, symbolic_u0::Bool, kwargs::@Kwargs{})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/problem_utils.jl:463
 [12] process_SciMLProblem
    @ ~/.julia/packages/ModelingToolkit/duznJ/src/systems/problem_utils.jl:410 [inlined]
 [13] (ODEProblem{…})(sys::ODESystem, u0map::Vector{…}, tspan::Tuple{…}, parammap::SciMLBase.NullParameters; callback::Nothing, check_length::Bool, warn_initialize_determined::Bool, eval_expression::Bool, eval_module::Module, kwargs::@Kwargs{})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:811
 [14] ODEProblem
    @ ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:799 [inlined]
 [15] (ODEProblem{true, SciMLBase.AutoSpecialize})(sys::ODESystem, u0map::Vector{Any}, tspan::Tuple{Int64, Int64})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:799
 [16] (ODEProblem{true})(::ODESystem, ::Vector{Any}, ::Vararg{Any}; kwargs::@Kwargs{})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:786
 [17] (ODEProblem{true})(::ODESystem, ::Vector{Any}, ::Vararg{Any})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:785
 [18] ODEProblem(::ODESystem, ::Vector{Any}, ::Vararg{Any}; kwargs::@Kwargs{})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:775
 [19] ODEProblem(::ODESystem, ::Vector{Any}, ::Vararg{Any})
    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/duznJ/src/systems/diffeqs/abstractodesystem.jl:774
 [20] top-level scope
    @ REPL[9]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `REDACTED/Project.toml`
  [961ee093] ModelingToolkit v9.48.0
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
Status `REDACTED/Manifest.toml`
  [47edcb42] ADTypes v1.9.0
  [1520ce14] AbstractTrees v0.4.5
  [7d9f7c33] Accessors v0.1.38
  [79e6a3ab] Adapt v4.1.0
  [66dad0bd] AliasTables v1.1.3
  [ec485272] ArnoldiMethod v0.4.0
  [4fba245c] ArrayInterface v7.16.0
  [4c555306] ArrayLayouts v1.10.4
  [e2ed5e7c] Bijections v0.1.9
  [62783981] BitTwiddlingConvenienceFunctions v0.1.6
  [8e7c35d0] BlockArrays v1.1.1
  [2a0fbf3d] CPUSummary v0.2.6
  [00ebfdb7] CSTParser v3.4.3
  [d360d2e6] ChainRulesCore v1.25.0
  [fb6a15b2] CloseOpenIntervals v0.1.13
  [861a8166] Combinatorics v1.0.2
  [a80b9123] CommonMark v0.8.15
  [38540f10] CommonSolve v0.2.4
  [bbf7d656] CommonSubexpressions v0.3.1
  [f70d9fcc] CommonWorldInvalidations v1.0.0
  [34da2185] Compat v4.16.0
  [b152e2b5] CompositeTypes v0.1.4
  [a33af91c] CompositionsBase v0.1.2
  [2569d6c7] ConcreteStructs v0.2.3
  [187b0558] ConstructionBase v1.5.8
  [adafc99b] CpuId v0.3.1
  [a8cc5b0e] Crayons v4.1.1
  [9a962f9c] DataAPI v1.16.0
  [864edb3b] DataStructures v0.18.20
  [e2d170a0] DataValueInterfaces v1.0.0
  [2b5f629d] DiffEqBase v6.158.3
  [459566f4] DiffEqCallbacks v4.0.0
  [77a26b50] DiffEqNoiseProcess v5.23.0
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [a0c0ee7d] DifferentiationInterface v0.6.16
  [8d63f2c5] DispatchDoctor v0.4.17
  [31c24e10] Distributions v0.25.112
  [ffbed154] DocStringExtensions v0.9.3
  [5b8099bc] DomainSets v0.7.14
  [7c1d4256] DynamicPolynomials v0.6.0
  [06fc5a27] DynamicQuantities v1.1.0
  [4e289a0a] EnumX v1.0.4
  [f151be2c] EnzymeCore v0.8.4
  [e2ba6199] ExprTools v0.1.10
⌅ [6b7a57c9] Expronicon v0.8.5
  [7034ab61] FastBroadcast v0.3.5
  [9aa1b823] FastClosures v0.3.2
  [29a986be] FastLapackInterface v2.0.4
  [1a297f60] FillArrays v1.13.0
  [64ca27bc] FindFirstFunctions v1.4.1
  [6a86dc24] FiniteDiff v2.26.0
  [1fa38f19] Format v1.3.7
  [f6369f11] ForwardDiff v0.10.36
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [d9f16b24] Functors v0.4.12
⌅ [46192b85] GPUArraysCore v0.1.6
  [c27321d9] Glob v1.3.1
  [86223c79] Graphs v1.12.0
  [3e5b6fbb] HostCPUFeatures v0.1.17
  [34004b35] HypergeometricFunctions v0.3.24
  [615f187c] IfElse v0.1.1
  [d25df0c9] Inflate v0.1.5
  [18e54dd8] IntegerMathUtils v0.1.2
  [8197267c] IntervalSets v0.7.10
  [3587e190] InverseFunctions v0.1.17
  [92d709cd] IrrationalConstants v0.2.2
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.6.1
  [98e50ef6] JuliaFormatter v1.0.62
  [ccbc3e58] JumpProcesses v9.14.0
  [ef3ab10e] KLU v0.6.0
  [ba0b0d4f] Krylov v0.9.8
  [b964fa9f] LaTeXStrings v1.4.0
  [23fbe1c1] Latexify v0.16.5
  [10f19ff3] LayoutPointers v0.1.17
  [5078a376] LazyArrays v2.2.1
  [87fe0de2] LineSearch v0.1.4
  [d3d80556] LineSearches v7.3.0
  [7ed4a6bd] LinearSolve v2.36.1
  [2ab3a3ac] LogExpFunctions v0.3.28
  [bdcacae8] LoopVectorization v0.12.171
  [d8e11817] MLStyle v0.4.17
  [1914dd2f] MacroTools v0.5.13
  [d125e4d3] ManualMemory v0.1.8
  [bb5d69b7] MaybeInplace v0.1.4
  [e1d29d7a] Missings v1.2.0
  [961ee093] ModelingToolkit v9.48.0
  [46d2c3a1] MuladdMacro v0.2.4
  [102ac46a] MultivariatePolynomials v0.5.7
  [d8a4904e] MutableArithmetics v1.5.2
  [d41bc354] NLSolversBase v7.8.3
  [77ba4419] NaNMath v1.0.2
  [8913a72c] NonlinearSolve v3.15.1
  [6fe1bfb0] OffsetArrays v1.14.1
  [429524aa] Optim v1.9.4
  [bac558e1] OrderedCollections v1.6.3
  [90014a1f] PDMats v0.11.31
  [65ce6f38] PackageExtensionCompat v1.0.2
  [d96e819e] Parameters v0.12.3
  [e409e4f3] PoissonRandom v0.4.4
  [f517fe37] Polyester v0.7.16
  [1d0040c9] PolyesterWeave v0.2.2
  [85a6dd25] PositiveFactorizations v0.2.4
  [d236fae5] PreallocationTools v0.4.24
  [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [27ebfcd6] Primes v0.5.6
  [43287f4e] PtrArrays v1.2.1
  [1fd47b50] QuadGK v2.11.1
  [74087812] Random123 v1.7.0
  [e6cf234a] RandomNumbers v1.6.0
  [3cdcf5f2] RecipesBase v1.3.4
  [731186ca] RecursiveArrayTools v3.27.0
  [f2c3362d] RecursiveFactorization v0.2.23
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.0
  [ae5879a3] ResettableStacks v1.1.1
  [79098fc4] Rmath v0.8.0
  [7e49a35a] RuntimeGeneratedFunctions v0.5.13
  [94e857df] SIMDTypes v0.1.0
  [476501e8] SLEEFPirates v0.6.43
  [0bca4576] SciMLBase v2.57.1
  [19f34311] SciMLJacobianOperators v0.1.0
  [c0aeaf25] SciMLOperators v0.3.11
  [53ae85a6] SciMLStructures v1.5.0
  [efcf1570] Setfield v1.1.1
  [727e6d20] SimpleNonlinearSolve v1.12.3
  [699a6c99] SimpleTraits v0.9.4
  [a2af1166] SortingAlgorithms v1.2.1
  [9f842d2f] SparseConnectivityTracer v0.6.8
  [0a514795] SparseMatrixColorings v0.4.8
  [e56a9233] Sparspak v0.3.9
  [276daf66] SpecialFunctions v2.4.0
  [aedffcd0] Static v1.1.1
  [0d7ed370] StaticArrayInterface v1.8.0
  [90137ffa] StaticArrays v1.9.8
  [1e83bf80] StaticArraysCore v1.4.3
  [10745b16] Statistics v1.11.1
  [82ae8749] StatsAPI v1.7.0
  [2913bbd2] StatsBase v0.34.3
  [4c63d2b9] StatsFuns v1.3.2
  [7792a7ef] StrideArraysCore v0.5.7
  [2efcf032] SymbolicIndexingInterface v0.3.33
  [19f23fe9] SymbolicLimits v0.2.2
  [d1185830] SymbolicUtils v3.7.2
  [0c5d862f] Symbolics v6.16.0
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.12.0
  [8ea1fca8] TermInterface v2.0.0
  [1c621080] TestItems v1.0.0
  [8290d209] ThreadingUtilities v0.5.2
  [a759f4b9] TimerOutputs v0.5.25
  [0796e94c] Tokenize v0.5.29
  [d5829a12] TriangularSolve v0.2.1
  [410a4b4d] Tricks v0.1.9
  [781d530d] TruncatedStacktraces v1.4.0
  [5c2747f8] URIs v1.5.1
  [3a884ed6] UnPack v1.0.2
  [1986cc42] Unitful v1.21.0
  [a7c27f48] Unityper v0.1.6
  [3d5dd08c] VectorizationBase v0.21.70
  [1d5cc7b8] IntelOpenMP_jll v2024.2.1+0
  [856f044c] MKL_jll v2024.2.0+0
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [f50d1b31] Rmath_jll v0.5.1+0
  [1317d2d5] oneTBB_jll v2021.12.0+0
  [0dad84c5] ArgTools v1.1.2
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [ade2ca70] Dates v1.11.0
  [8ba89e20] Distributed v1.11.0
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching v1.11.0
  [9fa8497b] Future v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [4af54fe1] LazyArtifacts v1.11.0
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2 v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.11.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [a63ad114] Mmap v1.11.0
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.11.0
  [de0858da] Printf v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [1a1011a3] SharedArrays v1.11.0
  [6462fe0b] Sockets v1.11.0
  [2f01184e] SparseArrays v1.11.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test v1.11.0
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [deac9b47] LibCURL_jll v8.6.0+0
  [e37daf67] LibGit2_jll v1.7.2+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.6+0
  [14a3606d] MozillaCACerts_jll v2023.12.12
  [4536629a] OpenBLAS_jll v0.3.27+1
  [05823500] OpenLibm_jll v0.8.1+2
  [bea87d4a] SuiteSparse_jll v7.7.0+0
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.11.0+0
  [8e850ede] nghttp2_jll v1.59.0+0
  [3f19e933] p7zip_jll v17.4.0+2
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
```

  - Output of `versioninfo()`

```julia
Julia Version 1.11.1
Commit 8f5b7ca12ad (2024-10-16 10:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × 12th Gen Intel(R) Core(TM) i7-12700
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, alderlake)
Threads: 1 default, 0 interactive, 1 GC (on 20 virtual cores)
```

**Additional context**

I'm currently working on a library building on top of ModelingToolkit which aims to simulate biochemical reactions (especially for wastewater treatment). Applying it to one of these plants, this error occurred (in a much more complex model). Doing the rewriting myself would not be feasible due to the complexity of the overall model.

**Comment by AayushSabharwal** [comment]
While the error message is a little misleading and should be fixed, this isn't a bug. In the first ("not working") system, `S_sep_out2` is an unknown and needs an initial value, which can't be calculated given just the defaults and observed in the system:

```julia
julia> sys_simplified = structural_simplify(sys)
Model sys with 1 equations
Unknowns (1):
  S_sep_out2(t)
Parameters (2):
  S_in [defaults to 1]
  q_in [defaults to 1]

julia> observed(sys_simplified)
5-element Vector{Equation}:
 S(t) ~ q_in
 q(t) ~ S_in
 q_sep_out2(t) ~ 0.5
 S_sep_out1(t) ~ S_sep_out2(t)
 q_sep_out1(t) ~ -q_sep_out2(t) + q(t)
```

Since `S_sep_out2` doesn't have a guess, it can't be solved for during initialization either. Providing the guess works:
```julia
julia> prob = ODEProblem(sys_simplified, [], (0, 1); guesses = [S_sep_out2 => 0.1])
ODEProblem with uType Vector{Float64} and tType Int64. In-place: true
timespan: (0, 1)
u0: 1-element Vector{Float64}:
 0.0

julia> sol = solve(prob, Rodas5())
┌ Warning: Rosenbrock methods on equations without differential states do not bound the error on interpolations.
└ @ OrdinaryDiffEqCore ~/Julia/SciML/OrdinaryDiffEq.jl/lib/OrdinaryDiffEqCore/src/solve.jl:108
retcode: Success
Interpolation: specialized 4rd order "free" stiffness-aware interpolation
t: 8-element Vector{Float64}:
 0.0
 1.0e-6
 1.1e-5
 0.00011099999999999999
 0.0011109999999999998
 0.011110999999999996
 0.11111099999999996
 1.0
u: 8-element Vector{Vector{Float64}}:
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
 [1.0]
```

The solution is constant because this is a system of nonlinear equations, not a DAE/ODE; there are no differential equations.

As for your "working" example, `structural_simplify` can analytically solve the system and thus you end up with one that has zero unknowns:

```julia
julia> sys_simplified = structural_simplify(sys)
Model sys with 0 equations
Unknowns (0):
Parameters (2):
  S_in [defaults to 1]
  q_in [defaults to 1]
```

And creating the `ODEProblem` works, because there are no unknowns that need an initial value.

**Comment by wenflo** [comment]
Thanks a lot for the quick and detailed reply! It is very helpful and makes sense to me.

Indeed the error message is misleading (especially also since the wrong variable is mentioned, `S_sep_out1` while `S_sep_out2` needs the guess). But knowing this, I could fix this issue in the larger problem as well.

However, now, I'm running into another problem, and this is that the simulation seems to get stuck in the initialization (takes over 1h and I put in a progress printing callback which gets never called until then). I'm still working on it to make a MWE and might come back if I manage to create one.

But a general question regarding guesses: Can it be a problem if too many guesses are provided? Or are the additional (for variables removed during simplification) just ignored?

**Comment by AayushSabharwal** [comment]
Too many guesses shouldn't be a problem. As for the infinite loop, I fixed an infinite loop in Symbolics@6.15.4. Does updating to that version (or later) help?

**Comment by wenflo** [comment]
I just updated and tested now with ModelingToolkit@9.49.0 and Symbolics@6.16.0 and I'm still facing the infinite loop. Now, however, once I canceled now after ~20min it showed an `InitialFailure` response code. I continue on trying to produce an MWE and come back to you once I have it (or a reason why it occurred)

**Comment by wenflo** [comment]
Ok nevermind. It seems that I just selected especially bad initial guesses which apparently made solving the initialization system taking a very long time (~30min, thus before it was most likely indeed the one you fixed in Symbolics and now it was just taking a very long time). Picking better initial conditions now yielded a faster response and a physically sensible result.

Thanks a lot for your help! Shall I close this issue then?

**Comment by ChrisRackauckas** [comment]
> long time (~30min, thus before it was most likely indeed the one you fixed in Symbolics and now it was just taking a very long time

That's probably the maxiters on the recursion detection. 30 minutes would be too high 😅, we should probably make the maxiters a bit lower.

**Comment by wenflo** [comment]
I agree that this is a very long time. But I guess this depends on the number (and size) of loops that are there.

I work with a system that has ~450 unknowns after simplification and in there are 6 loops which are interconnected. +1 additional loop over all of these 6 together. So I guess I have quite some loops involved here :sweat_smile: (Although only few of them are algebraic, I guess the only case where substitutions are involved)

I guess how many iterations there are made, depends on how the maxiters are implemented: if they are applied to all substitutions together (i.e. it is an absolute limit on substitutions) or per-iteration (i.e. limit on applying the same substitution circle, thus in each iteration of the outer loop it could make maxiters iterations on the inner ones).
