### ISSUE TITLE
Inversion of anti-symmetric matrix fails

### ISSUE THREAD

**Issue by michakraus** [SciML/ModelingToolkit.jl#622]
Inversion of (even-dimensional) anti-symmetric matrices fails:
```julia
julia> inv([ Num(0)  -Num(1)
            +Num(1)   Num(0)])
ERROR: ZeroPivotException: factorization encountered one or more zero pivots. Consider switching to a pivoted LU factorization.
Stacktrace:
 [1] checknonsingular at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/factorization.jl:20 [inlined]
 [2] generic_lufact!(::Array{Num,2}, ::Val{false}; check::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/lu.jl:178
 [3] #lu!#134 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/lu.jl:130 [inlined]
 [4] #lu#136 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/lu.jl:273 [inlined]
 [5] lu at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/lu.jl:272 [inlined]
 [6] #lu#5 at ~/.julia/packages/ModelingToolkit/QPQyE/src/ModelingToolkit.jl:126 [inlined]
 [7] lu at ~/.julia/packages/ModelingToolkit/QPQyE/src/ModelingToolkit.jl:126 [inlined]
 [8] inv(::Array{Num,2}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/dense.jl:781
 [9] top-level scope at REPL[4]:1
```
while
```julia
julia> inv([ 0  -1
            +1   0])
2×2 Array{Float64,2}:
  0.0  1.0
 -1.0  0.0
```

**Comment by YingboMa** [comment]
This is fixed by #683

**Comment by michakraus** [comment]
Thanks, `solve_for` does indeed work now for a non-constant anti-symmetric matrix. However, with MTK v4.5.0 I still get the `ZeroPivotException` for
```julia
> inv(Num.([ 0  -1
             1   0 ]))
```
and the same for the non-constant matrix from above.

**Comment by YingboMa** [comment]
I cannot reproduce that. Did you restart Julia after upgrading?

See
```julia
julia> (α,) = @variables α[1:2]
(Num[α₁, α₂],)

julia> (β,) = @variables β[1:2]
(Num[β₁, β₂],)

julia> @parameters t
(t,)

julia> @variables x₁(t), x₂(t)
(x₁(t), x₂(t))

julia> Ω = [ Num(0)  -x₁*x₂
            +x₁*x₂   Num(0)]
2×2 Matrix{Num}:
           0  -1x₁(t)*x₂(t)
 x₁(t)*x₂(t)              0

julia> lhs = simplify.(Ω * α)
2-element Vector{Num}:
 -1x₁(t)*x₂(t)*α₂
   x₁(t)*x₂(t)*α₁

julia> equs = [Equation(lhs[i], β[i]) for i in eachindex(lhs,β)]
2-element Vector{Equation}:
 Equation(-1x₁(t)*x₂(t)*α₂, β₁)
 Equation(x₁(t)*x₂(t)*α₁, β₂)

julia> ModelingToolkit.solve_for(equs, α)
2-element Vector{SymbolicUtils.Mul{Number, Int64, Dict{Any, Number}}}:
 (x₁(t)^-1)*(x₂(t)^-1)*β₂
 -1(x₁(t)^-1)*(x₂(t)^-1)*β₁
```
and
```julia
julia> inv(Num.([ 0  -1
                    1   0 ]))
2×2 Matrix{Num}:
  0.0   1.0
 -1.0  -0.0
```

**Comment by michakraus** [comment]
Ha, there is something strange going on. Indeed I restarted, and I ran in a Jupyter notebook. If I run in the REPL, everything works, but in the Jupyter Notebook I get a `ZeroPivotException`. Both running Julia v1.5.3, both freshly started... `solve_for` works in both, but not `inv`.

**Comment by michakraus** [comment]
I found another issue with the 4d version of the above example:
```julia
julia> Ω = [ 0        -1/x₁/x₂  +1/x₁/x₃   -1/x₁/x₄
            +1/x₂/x₁   0        -1/x₂/x₃   +1/x₂/x₄
            -1/x₃/x₁  +1/x₃/x₂   0         -1/x₃/x₄
            +1/x₄/x₁  -1/x₄/x₂  +1/x₄/x₃    0      ]
4×4 Matrix{Num}:
                                                                                                                                                                0  …  (-1 / x₁(t)) / x₄(t)
  (1 / x₂(t)) / x₁(t)      (1 / x₂(t)) / x₄(t)
 (-1 / x₃(t)) / x₁(t)     (-1 / x₃(t)) / x₄(t)
  (1 / x₄(t)) / x₁(t)                                                                                                                                                                    0

julia> P = simplify.(inv(Ω))
4×4 Array{Num,2}:
(0 ^ -1) * (x₁(t) ^ 2) * (x₃(t) ^ -2)                                                                                                                                                                                                                                                                                                                                                                                                                                                  …  x₁(t) * x₄(t) * (x₃(t) ^ -2)
                                                                                                                                                                                                                                                                                                   -1.0 * x₁(t) * x₂(t) * (1 + (-1 * (0 ^ -1) * (x₃(t) ^ -2)))                                                                                                                                                                                                                              0.0
                                                         x₁(t) * (0 ^ -1) * (x₃(t) ^ -1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               x₄(t) * (x₃(t) ^ -1)
                                                                                                                                                                                                                                                                                                        -0.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            0.0
```
The problem being the `(0 ^ -1)`'s. If I didn't introduce some stupid typo, that thing should be invertible.

**Comment by YingboMa** [comment]
The master branch of MTK gives
```julia
julia> P = simplify.(inv(Ω))
4×4 Matrix{Num}:
                   0          x₁(t)*x₂(t)          x₁(t)*x₃(t)  x₁(t)*x₄(t)
 (-1//1)*x₁(t)*x₂(t)                    0          x₂(t)*x₃(t)  x₂(t)*x₄(t)
 (-1//1)*x₁(t)*x₃(t)  (-1//1)*x₂(t)*x₃(t)                    0  x₃(t)*x₄(t)
 (-1//1)*x₁(t)*x₄(t)  (-1//1)*x₂(t)*x₄(t)  (-1//1)*x₃(t)*x₄(t)            0
```

**Comment by ChrisRackauckas** [comment]
`(-1//1)` intentional?

**Comment by YingboMa** [comment]
Yes, it's deliberate, SymbolicUtils.jl's canonicalization doesn't have operator `-`. There's only `-1*x`

Also, this problem cannot be solved in general, since it amounts to test whether a set of arbitrary expressions is 0 under `+, -, /, *`.

**Comment by ChrisRackauckas** [comment]
But I would assume `//` can get simplified away when it has a 1 or a zero? That looks like a missing rule.

**Comment by YingboMa** [comment]
Yeah, that can be done.

**Comment by YingboMa** [comment]
Or we can just fix the printing? Since it doesn't actually affect the evaluation speed.

**Comment by ChrisRackauckas** [comment]
Why wouldn't you want to simplify away rationals?

**Comment by YingboMa** [comment]
Adding that rule in canonicalization introduces an overhead everywhere in the construction, and it makes construction of terms type unstable.

**Comment by ChrisRackauckas** [comment]
I see. Fixing the printing may be the way to go then.

**Comment by YingboMa** [comment]
We can simplify those trivial simplification when converting to an Expr if needed. We already need to do some of that in https://github.com/SciML/ModelingToolkit.jl/blob/135821e06a4b0e16adb62c0ad87410cf1d57c20e/src/direct.jl#L244-L265

Though, it doesn't change the asm at all.
```julia
julia> foo(x) = 2//1 * x
foo (generic function with 1 method)

julia> goo(x) = 2 * x
goo (generic function with 1 method)

julia> @code_native debuginfo=:none foo(1.2)
        .section        __TEXT,__text,regular,pure_instructions
        vaddsd  %xmm0, %xmm0, %xmm0
        retq
        nopw    %cs:(%rax,%rax)

julia> @code_native debuginfo=:none goo(1.2)
        .section        __TEXT,__text,regular,pure_instructions
        vaddsd  %xmm0, %xmm0, %xmm0
        retq
        nopw    %cs:(%rax,%rax)
```

**Comment by ChrisRackauckas** [comment]
Yeah then just do the printing.
